<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>


<script>
  /**
   * Promise的流程图,无论是then还是catch都可以返回一个promise对象.
   * 所以代码可以进行链式调用
   *
   */

//  网络请求aaa -> 自己处理5行 继续
//  处理aaa111 -> 自己处理5行 继续
//  处理aaa111222 -> 自己处理

  //注意then跟随的地方

  new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('aaa')
    }, 1000)
  }).then((data) => {
    console.log(data)

    // 本来即将执行完,但因为一个return回去,之前执行的又变成了一个Promise的对象,又可以继续then了,链式起来了.
    return new Promise((resolve, reject) => {
      resolve(data + '111')
    })
  }).then((data) => {
    console.log(data)

    // 可以简写为如下代码
    return  Promise.resolve(data + '2222')
  }).then((data) => {
    console.log(data)

    // 异常抛出
    // return Promise.reject('error message')
    // 手动抛出异常
    // throw 'error message'

    // 还可以继续简化, 内部会做resolve处理
    return  data + '3333'
  }).then((data) => {
    console.log(data)
  //  不论多少个reject,只需要一个catch, 捕获到一个reject,就直接到catch了
  }).catch((err) => {
    console.log(err)
  })
</script>


</body>
</html>